/*
 * TemplateManager.java
 *
 * This file is part of JIF.
 *
 * Jif is substantially an editor entirely written in java that allows the
 * file management for the creation of text-adventures based on Graham
 * Nelson's Inform standard [a programming language for Interactive Fiction].
 * With Jif, it's possible to edit, compile and run a Text Adventure in
 * Inform format.
 *
 * Copyright (C) 2004  Alessandro Schillaci
 *
 * WeB   : http://www.slade.altervista.org/JIF/
 * e-m@il: silver.slade@tiscalinet.it
 *
 * Jif is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jif; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

import java.io.*;
import javax.swing.*;
import javax.swing.tree.*;
import java.util.*;
import java.awt.*;

/**
 * Class for the management of Templates
 * Static/Dynamic Templates are Inform code files
 * by category/language and ready to be used in you inform
 * game
 * @author Alessandro Schillaci
 */
public class TemplateManager extends javax.swing.JFrame {
    jFrame parent = null;

    /**
     * Creates new instance of TemplateManager
     * @param file The template directory location
     */
    public TemplateManager(String file) {
        this.templateDirectory = file;
        initComponents();
        loadTemplates(file);
    }

    /**
     * Creates new instance of TemplateManager
     * @param parent Instance of jFrame
     * @param file The template directory location
     */
    public TemplateManager(jFrame parent, String file) {
        ICON_STATIC = new ImageIcon(getClass().getResource("/images/TREE_static.png"));
        ICON_DINAMIC = new ImageIcon(getClass().getResource("/images/TREE_dynamic.png"));

        this.templateDirectory = file;
        this.parent = parent;
        initComponents();

        loadTemplates(file);

        // Expanding the first level
        expandFirstLevel(this.jTreeTemplate);
        this.setSize(700,600);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jFrameStatico = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldVersion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTargetDirectory = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButtonSaveStatic = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaStaticCode = new javax.swing.JTextArea();
        jFrameDinamico = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNameDynamic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAuthorDynamic = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDateDynamic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVersionDynamic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDescriptionDynamic = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTargetDirectoryDynamic = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jButtonSaveDynamic = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDynamicCode = new javax.swing.JTextArea();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCode = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jButtonUseSelected = new javax.swing.JButton();
        jButtonMakeIstance = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButtonRefreshTree = new javax.swing.JButton();
        jButtonNewDirectory = new javax.swing.JButton();
        jButtonNewStatic = new javax.swing.JButton();
        jButtonNewDynamic = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonMake = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeTemplate = new javax.swing.JTree();
        top = new DefaultMutableTreeNode(new Template(templateDirectory,new File(templateDirectory)));
        //Create a tree that allows one selection at a time.
        treeModel = new DefaultTreeModel(top);
        jTreeTemplate = new JTree(treeModel);
        jTreeTemplate.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        //jTreeTemplate.setCellRenderer(renderer);

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        jFrameStatico.setTitle(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMESTATICO_TITLE"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(6, 2, -150, 0));

        jLabel1.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMESTATICO_NAME"));
        jPanel4.add(jLabel1);

        jPanel4.add(jTextFieldName);

        jLabel2.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMESTATICO_AUTHOR"));
        jPanel4.add(jLabel2);

        jPanel4.add(jTextFieldAuthor);

        jLabel3.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMESTATICO_DATE"));
        jPanel4.add(jLabel3);

        jPanel4.add(jTextFieldDate);

        jLabel4.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMESTATICO_VERSION"));
        jPanel4.add(jLabel4);

        jPanel4.add(jTextFieldVersion);

        jLabel5.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMESTATICO_DESCRIPTION"));
        jPanel4.add(jLabel5);

        jPanel4.add(jTextFieldDescription);

        jLabel6.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMESTATICO_DESTINATION_PATH"));
        jPanel4.add(jLabel6);

        jTextFieldTargetDirectory.setEditable(false);
        jPanel4.add(jTextFieldTargetDirectory);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        jButtonSaveStatic.setText(java.util.ResourceBundle.getBundle("JIF").getString("MESSAGE_SAVE"));
        jButtonSaveStatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveStaticActionPerformed(evt);
            }
        });

        jPanel5.add(jButtonSaveStatic);

        jButton3.setToolTipText("");
        jButton3.setText(java.util.ResourceBundle.getBundle("JIF").getString("MESSAGE_CANCEL"));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel5.add(jButton3);

        jPanel3.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jScrollPane4.setViewportView(jTextAreaStaticCode);

        jPanel3.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jFrameStatico.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jFrameDinamico.setTitle(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMEDINAMICO_TITLE"));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.GridLayout(6, 2, -150, 0));

        jLabel7.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMEDINAMICO_NAME"));
        jPanel10.add(jLabel7);

        jPanel10.add(jTextFieldNameDynamic);

        jLabel8.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMEDINAMICO_AUTHOR"));
        jPanel10.add(jLabel8);

        jPanel10.add(jTextFieldAuthorDynamic);

        jLabel9.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMEDINAMICO_DATE"));
        jPanel10.add(jLabel9);

        jPanel10.add(jTextFieldDateDynamic);

        jLabel10.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMEDINAMICO_VERSION"));
        jPanel10.add(jLabel10);

        jPanel10.add(jTextFieldVersionDynamic);

        jLabel11.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMEDINAMICO_DESCRIPTION"));
        jPanel10.add(jLabel11);

        jPanel10.add(jTextFieldDescriptionDynamic);

        jLabel12.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_JFRAMEDINAMICO_DESTINATION_PATH"));
        jPanel10.add(jLabel12);

        jTextFieldTargetDirectoryDynamic.setEditable(false);
        jPanel10.add(jTextFieldTargetDirectoryDynamic);

        jPanel9.add(jPanel10, java.awt.BorderLayout.NORTH);

        jButtonSaveDynamic.setText(java.util.ResourceBundle.getBundle("JIF").getString("MESSAGE_SAVE"));
        jButtonSaveDynamic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDynamicActionPerformed(evt);
            }
        });

        jPanel11.add(jButtonSaveDynamic);

        jButton7.setToolTipText("");
        jButton7.setText(java.util.ResourceBundle.getBundle("JIF").getString("MESSAGE_CANCEL"));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel11.add(jButton7);

        jPanel9.add(jPanel11, java.awt.BorderLayout.SOUTH);

        jScrollPane5.setViewportView(jTextAreaDynamicCode);

        jPanel9.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jFrameDinamico.getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        setTitle(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_TITLE"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jSplitPane2.setDividerSize(3);
        jSplitPane2.setMinimumSize(new java.awt.Dimension(500, 500));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(700, 600));
        jSplitPane2.setAutoscrolls(true);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 300));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 200));
        jTextAreaCode.setEditable(false);
        jTextAreaCode.setTabSize(4);
        jTextAreaCode.setFont(new java.awt.Font("Monospaced", 0, 12));
        jScrollPane2.setViewportView(jTextAreaCode);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(500, 19));
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setEditable(false);
        jTextAreaDescription.setTabSize(4);
        jTextAreaDescription.setFont(new java.awt.Font("Monospaced", 0, 11));
        jScrollPane3.setViewportView(jTextAreaDescription);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jButtonUseSelected.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_USE_SELECTED_TEMPLATE_TOOLTIP"));
        jButtonUseSelected.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_USE_SELECTED_TEMPLATE"));
        jButtonUseSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUseSelectedActionPerformed(evt);
            }
        });

        jPanel6.add(jButtonUseSelected);

        jButtonMakeIstance.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_MAKE_ISTANCE_TOOLTIP"));
        jButtonMakeIstance.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_MAKE_ISTANCE"));
        jButtonMakeIstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeIstanceActionPerformed(evt);
            }
        });

        jPanel6.add(jButtonMakeIstance);

        jPanel2.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPanel2);

        jSplitPane2.setRightComponent(jSplitPane1);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(180, 100));
        jPanel7.setMinimumSize(new java.awt.Dimension(180, 100));
        jPanel7.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel8.setMinimumSize(new java.awt.Dimension(150, 100));
        jPanel8.setMaximumSize(new java.awt.Dimension(0, 0));
        jButtonRefreshTree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tree.gif")));
        jButtonRefreshTree.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_REFRESHTREE_TOOLTIP"));
        jButtonRefreshTree.setPreferredSize(new java.awt.Dimension(30, 27));
        jButtonRefreshTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshTreeActionPerformed(evt);
            }
        });

        jPanel8.add(jButtonRefreshTree);

        jButtonNewDirectory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filenew.png")));
        jButtonNewDirectory.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_NEW_DIRECTORY_TOOLTIP"));
        jButtonNewDirectory.setPreferredSize(new java.awt.Dimension(30, 27));
        jButtonNewDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewDirectoryActionPerformed(evt);
            }
        });

        jPanel8.add(jButtonNewDirectory);

        jButtonNewStatic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newTemplateStatic.gif")));
        jButtonNewStatic.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_NEW_STATIC_TEMPLATE_TOOLTIP"));
        jButtonNewStatic.setPreferredSize(new java.awt.Dimension(30, 27));
        jButtonNewStatic.setEnabled(false);
        jButtonNewStatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStaticActionPerformed(evt);
            }
        });

        jPanel8.add(jButtonNewStatic);

        jButtonNewDynamic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newTemplateDynamic.gif")));
        jButtonNewDynamic.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_NEW_DYNAMIC_TEMPLATE_TOOLTIP"));
        jButtonNewDynamic.setPreferredSize(new java.awt.Dimension(30, 27));
        jButtonNewDynamic.setEnabled(false);
        jButtonNewDynamic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewDynamicActionPerformed(evt);
            }
        });

        jPanel8.add(jButtonNewDynamic);

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif")));
        jButtonDelete.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_DELETE_SELECTED_TEMPLATE_TOOLTIP"));
        jButtonDelete.setPreferredSize(new java.awt.Dimension(30, 27));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jPanel8.add(jButtonDelete);

        jButtonMake.setToolTipText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_MAKE_TEMPLATE_FILE_TOOLTIP"));
        jButtonMake.setText(java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATE_MANAGER_ MAKE_TEMPLATE_FILE"));
        jButtonMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeActionPerformed(evt);
            }
        });

        jPanel8.add(jButtonMake);

        jPanel7.add(jPanel8, java.awt.BorderLayout.NORTH);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(150, 200));
        jScrollPane1.setDoubleBuffered(true);
        jTreeTemplate.setCellRenderer(new TemplateRenderer());
        jTreeTemplate.setDoubleBuffered(true);
        jTreeTemplate.setExpandsSelectedPaths(false);
        jTreeTemplate.setLargeModel(true);
        jTreeTemplate.setMaximumSize(new java.awt.Dimension(0, 0));
        jTreeTemplate.setPreferredSize(new java.awt.Dimension(200, 1000));
        jTreeTemplate.setScrollsOnExpand(false);
        jTreeTemplate.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeTemplateValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jTreeTemplate);
        jTreeTemplate.getAccessibleContext().setAccessibleParent(jPanel7);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane2.setLeftComponent(jPanel7);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(255, 43));
        jPanel1.setMinimumSize(new java.awt.Dimension(255, 43));
        jButton4.setText(java.util.ResourceBundle.getBundle("JIF").getString("MENUITEM_EXIT"));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void jButtonMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeActionPerformed
        String result = JOptionPane.showInputDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_INSERT_FILE_NAME"));
        PrintStream ps;
        try{
            FileOutputStream fos = new FileOutputStream(new File(result));
            ps = new PrintStream( fos );
            ps.println (repository.toString());
            ps.close();
        } catch(IOException e ){System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButtonMakeActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       this.jFrameDinamico.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonNewDynamicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewDynamicActionPerformed
        Object nodo = ((DefaultMutableTreeNode)jTreeTemplate.getLastSelectedPathComponent()).getUserObject();
        File selected = ((Template)nodo).Tfile;
        this.directorySelected = selected;
        this.jTextFieldTargetDirectoryDynamic.setText(selected.getAbsolutePath());
        this.jFrameDinamico.setSize(400,400);
        Point p = this.getLocationOnScreen();
        p.move(100,100);
        this.jFrameDinamico.setLocation( p );
        this.jTextAreaDynamicCode.setText("");
        this.jTextFieldDescriptionDynamic.setText("");
        this.jTextFieldNameDynamic.setText("");
        this.jFrameDinamico.show();
    }//GEN-LAST:event_jButtonNewDynamicActionPerformed

    private void jButtonSaveDynamicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDynamicActionPerformed
        String parametri = getParameters();
        if (null==parametri) {
            this.jFrameDinamico.toFront();
            return;
        }
        StringBuffer sb = new StringBuffer();
        sb.append("# **** CREATED by JIF ****").append("\n\n")
        .append("# ---- DO NOT EDIT ----- ").append("\n\n")
        .append("[JIF TEMPLATE]").append("\n")
        .append("[TYPE]=dynamic").append("\n")
        .append("[NAME]="+this.jTextFieldNameDynamic.getText()).append("\n")
        .append("[AUTHOR]="+this.jTextFieldAuthorDynamic.getText()).append("\n")
        .append("[DATE]="+this.jTextFieldDateDynamic.getText()).append("\n")
        .append("[VERSION]="+this.jTextFieldVersionDynamic.getText()).append("\n")
        .append("[DESCRIPTION]="+this.jTextFieldDescriptionDynamic.getText()).append("\n")
        .append("[PARAMETERS_BEGIN]\n")
        .append(parametri)
        .append("[PARAMETERS_END]\n")
        .append("[BEGIN]").append("\n")
        .append(this.jTextAreaDynamicCode.getText()).append("\n")
        .append("[END]").append("\n")
        .append("# ---- DO NOT EDIT ----- ").append("\n\n");

        File file = new File(this.directorySelected.getAbsolutePath()+"\\"+this.jTextFieldNameDynamic.getText()+".jdt");
        PrintStream ps;

        // Saving the file
        try{
            FileOutputStream fos = new FileOutputStream(file);
            ps = new PrintStream( fos );
            ps.println (sb.toString());
            ps.flush();
            ps.close();
        }catch (IOException e){
            System.out.println(e.getMessage());
        }

        this.jFrameDinamico.hide();
        refreshTree();
    }//GEN-LAST:event_jButtonSaveDynamicActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        Object nodo = ((DefaultMutableTreeNode)jTreeTemplate.getLastSelectedPathComponent()).getUserObject();
        File selected = ((Template)nodo).Tfile;
        if (selected.isDirectory()){
            int result = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_DELETE_DIRECTORY")+selected.getAbsolutePath() , java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_ELIMINATE_DIRECTORY") , JOptionPane.YES_NO_OPTION);
            if (result == 0){
                // checks if the directory is empty
                if (selected.listFiles().length != 0){
                    result = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_DIRECTORY")+selected.getAbsolutePath()+java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_DIRECTORY_NOT_EMPTY_ERASE") , java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_CONFIRM_ERASE_DIRECTORY") , JOptionPane.YES_NO_OPTION);
                    if (result == 0){
                        deleteDir(selected);
                    }
                    else return;
                }
                else{
                    selected.delete();
                }
                    JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_DIRECTORY")+((Template)nodo).Tname+java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_DIRECTORY_ERASED"));
                    refreshTree();
            }
        }
        else {
            int result = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_DELETE_FILE")+selected.getAbsolutePath() , java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_ERASE_FILE") , JOptionPane.YES_NO_OPTION);
            if (result == 0){
                selected.delete();
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_TEMPLATE")+((Template)nodo).Tname+java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_HAS_BEEN_CANCELLED"));
                refreshTree();
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonNewDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewDirectoryActionPerformed
        Object nodo = ((DefaultMutableTreeNode)jTreeTemplate.getLastSelectedPathComponent()).getUserObject();
        File selected = ((Template)nodo).Tfile;
        String result = JOptionPane.showInputDialog(this , java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_INSERT_NAME_NEW_DIRECTORY"), java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_NEW_DIRECTORY"), JOptionPane.OK_CANCEL_OPTION);
        if (
        result.indexOf(".")!=-1 ||
        result.indexOf(" ")!=-1
        ){
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_WRONG_NAME"));
            return;
        }
        File file = new File(selected.getAbsolutePath()+"/"+result);
        file.mkdir();
        refreshTree();
    }//GEN-LAST:event_jButtonNewDirectoryActionPerformed

    private void jButtonMakeIstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeIstanceActionPerformed
        String tmp = this.jTextAreaCode.getText();
        String result="";

        if (this.jTextAreaDescription.getText().indexOf("[TYPE]=dynamic")!=-1){
            // Dinamic Template
            tmp = getDynamicTemplate();
            if (tmp.indexOf("Class")==-1){
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_TEMPLATE_ISNOT_CLASS"), java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_ERROR_ISTANCE"), JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!tmp.startsWith("Class")){
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_TEMPLATE_MUST_START_WITH_KEYWORD_\"Class\""), java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_ERROR_ISTANCE"), JOptionPane.WARNING_MESSAGE);
                return;
            }
            result = "Object"+tmp.substring(5);
            this.parent.insertFromTemplate(result);
        }
        else if (this.jTextAreaDescription.getText().indexOf("[TYPE]=static")!=-1){
            // Static Template
            if (tmp.indexOf("Class")==-1){
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_TEMPLATE_ISNOT_CLASS"), java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_ERROR_ISTANCE"), JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!tmp.startsWith("Class")){
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_TEMPLATE_MUST_START_WITH_KEYWORD_\"Class\""), java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_ERROR_ISTANCE"), JOptionPane.WARNING_MESSAGE);
                return;
            }
            result = "Object"+tmp.substring(5);
            this.parent.insertFromTemplate(result);
        }
        hide();
    }//GEN-LAST:event_jButtonMakeIstanceActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonSaveStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveStaticActionPerformed
        // Creates template string to be saved
        StringBuffer sb = new StringBuffer();
        sb.append("# **** MADE BY JIF ****").append("\n\n")
        .append("# ---- DO NOT EDIT ----- ").append("\n\n")
        .append("[JIF TEMPLATE]").append("\n")
        .append("[TYPE]=static").append("\n")
        .append("[NAME]="+this.jTextFieldName.getText()).append("\n")
        .append("[AUTHOR]="+this.jTextFieldAuthor.getText()).append("\n")
        .append("[DATE]="+this.jTextFieldDate.getText()).append("\n")
        .append("[VERSION]="+this.jTextFieldVersion.getText()).append("\n")
        .append("[DESCRIPTION]="+this.jTextFieldDescription.getText()).append("\n")
        .append("[BEGIN]").append("\n")
        .append(this.jTextAreaStaticCode.getText()).append("\n")
        .append("[END]").append("\n")
        .append("# ---- DO NOT EDIT ----- ").append("\n\n");
        File file = new File(this.directorySelected.getAbsolutePath()+"\\"+this.jTextFieldName.getText()+".jst");
        PrintStream ps;

        // Saving file
        try{
            FileOutputStream fos = new FileOutputStream(file);
            ps = new PrintStream( fos );
            ps.println (sb.toString());
            ps.flush();
            ps.close();
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
        this.jFrameStatico.hide();
        refreshTree();
    }//GEN-LAST:event_jButtonSaveStaticActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jFrameStatico.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonNewStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewStaticActionPerformed
        Object nodo = ((DefaultMutableTreeNode)jTreeTemplate.getLastSelectedPathComponent()).getUserObject();
        File selected = ((Template)nodo).Tfile;
        this.directorySelected = selected;
        this.jTextFieldTargetDirectory.setText(selected.getAbsolutePath());
        this.jFrameStatico.setSize(400,400);
        Point p = this.getLocationOnScreen();
        p.move(100,100);
        this.jFrameStatico.setLocation( p );
        this.jTextAreaStaticCode.setText("");
        this.jTextFieldDescription.setText("");
        this.jTextFieldName.setText("");
        this.jFrameStatico.show();
    }//GEN-LAST:event_jButtonNewStaticActionPerformed

    private void jButtonRefreshTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshTreeActionPerformed
        refreshTree();
    }//GEN-LAST:event_jButtonRefreshTreeActionPerformed

    private void jButtonUseSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUseSelectedActionPerformed
        if (this.jTextAreaDescription.getText().indexOf("[TYPE]=dynamic")!=-1){
            // Dinamic
            this.parent.insertFromTemplate(getDynamicTemplate());
        }
        else if (this.jTextAreaDescription.getText().indexOf("[TYPE]=static")!=-1){
            // Static
            this.parent.insertFromTemplate(getStaticTemplate());
        }
        hide();
    }//GEN-LAST:event_jButtonUseSelectedActionPerformed

    private void jTreeTemplateValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeTemplateValueChanged
        if (!refreshTree){
            Object nodo = ((DefaultMutableTreeNode)jTreeTemplate.getLastSelectedPathComponent()).getUserObject();
            File selected = ((Template)nodo).Tfile;
            if (
                selected.getAbsolutePath().indexOf(".jst")!=-1 ||
                selected.getAbsolutePath().indexOf(".jdt")!=-1
            ){
                // load textareas
                loadJt(selected);
                this.jButtonNewDynamic.setEnabled(false);
                this.jButtonNewStatic.setEnabled(false);
                this.jButtonNewDirectory.setEnabled(false);
                this.jButtonUseSelected.setEnabled(true);
                this.jButtonMakeIstance.setEnabled(true);
            }
            else if (selected.isDirectory()){
                this.jButtonNewDynamic.setEnabled(true);
                this.jButtonNewStatic.setEnabled(true);
                this.jButtonNewDirectory.setEnabled(true);
                this.jButtonUseSelected.setEnabled(false);
                this.jButtonMakeIstance.setEnabled(false);

                // Erases the textareas
                this.jTextAreaCode.setText("");
                this.jTextAreaDescription.setText("");
            }
        }
    }//GEN-LAST:event_jTreeTemplateValueChanged

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        hide();
    }//GEN-LAST:event_exitForm

    /**
     * Main method
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TemplateManager(templateDirectory).show();
    }


    /**
     * Load Temaplates into TemplateManager
     * @param directory Starting directory
     */
    public void loadTemplates(String directory){
        File templateDirectory = new File(directory);
        if (!templateDirectory.exists()) {
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_DIRECTORY_TEMPLATE_WRONG"));
        }
        repository = new StringBuffer();
        loadRecursive(top);
    }

    /**
     * Loading the Template Tree, from the starting
     * directory.
     *
     * 1. load current file
     * 2. if current file is a "file" (not a directory) return
     * 3. if current file is an "empty directory" return
     * 4. if current file is a directory with children:
     *    4.1) for each child, creates a node linking it to the "root" node
     *         and execute this method only if this file has the *.jdt
     *         or *.jst extensions
     *
     * The repository, is a StringBuffer with all the templates loaded.
     * @param root Current node
     */
    public void loadRecursive(DefaultMutableTreeNode root){
        DefaultMutableTreeNode current = null;
        Object nodo = root.getUserObject();
        Template template = (Template)nodo;

        if (template.Tfile.isFile()) {
            addTemplateToRepository(template);
            return;
        }
        if (template.Tfile.isDirectory() && template.Tfile.listFiles().length==0) return;
        if (template.Tfile.isDirectory()){
              File children[] = template.Tfile.listFiles();
              for (int count=0; count < children.length ; count++){
                    // Creates a new node
                    current = new DefaultMutableTreeNode(new Template(children[count].getName(),children[count]));
                    root.add(current);
                    loadRecursive(current);
              }
        }
    }

    /**
     * Loads template's informations into the textareas
     * @param file The template file
     */
    public void loadJt(File file){
        try{
            if (file.getAbsolutePath().endsWith(".jst")){
                // Static Template
                BufferedReader br = new BufferedReader(new FileReader(file));
                StringBuffer sbcode = new StringBuffer();
                StringBuffer sbdescr = new StringBuffer();
                String riga="";
                boolean markJifTemplate = false;    // false se il file non è nel formato di JIF
                boolean inCode = false;             // se sto parsando il codice
                boolean inDescription = false;      // se sto parsando la descrizione

                while ((riga = br.readLine())!=null){
                    if (!(riga.startsWith(Constants.TOKENCOMMENT))&&!(riga.equals(""))   ){
                        if (riga.equals("[JIF TEMPLATE]")) markJifTemplate=true;

                        // checking
                        if (
                        riga.startsWith("[TYPE]=") ||
                        riga.startsWith("[NAME]=") ||
                        riga.startsWith("[AUTHOR]=") ||
                        riga.startsWith("[DATE]=") ||
                        riga.startsWith("[VERSION]=") ||
                        riga.startsWith("[COMMENT]=") ||
                        riga.startsWith("[DESCRIPTION]=")
                        ){
                            if (riga.startsWith("[DESCRIPTION]=")) sbdescr
                            .append("[DESCRIPTION]\n").append(riga.substring(14)).append("\n");
                            else sbdescr.append(riga).append("\n");
                        }

                        if (riga.startsWith("[BEGIN]") ){ inCode=true;}
                        if (riga.startsWith("[END]") ){ inCode=false;}

                        else if (
                        !riga.startsWith("[BEGIN]") &&
                        !riga.startsWith("[END]") &&
                        !riga.startsWith("[JIF TEMPLATE]")
                        )
                        {
                            //flag per sapere se sono nel codice
                            if (inCode){
                                sbcode.append(riga).append("\n");
                            }
                        }
                    }
                }
                br.close();
                if (!markJifTemplate){
                    JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_WRONG_FORMAT_FILE"));
                }
                else {
                    // carico nelle text aree
                    this.jTextAreaCode.setText(sbcode.toString());
                    this.jTextAreaCode.setCaretPosition(0);
                    this.jTextAreaDescription.setText(sbdescr.toString());
                    this.jTextAreaDescription.setCaretPosition(0);
                }
            }
            else
            if (file.getAbsolutePath().endsWith(".jdt")){
                // Dymamic Template
                BufferedReader br = new BufferedReader(new FileReader(file));
                StringBuffer sbcode = new StringBuffer();
                StringBuffer sbdescr = new StringBuffer();
                String riga="";
                boolean markJifTemplate = false;    // false se il file non è nel formato di JIF
                boolean inCode = false;             // se sto parsando il codice
                boolean inDescription = false;      // se sto parsando la descrizione
                boolean inParameters = false;

                while ((riga = br.readLine())!=null){
                    if (!(riga.startsWith(Constants.TOKENCOMMENT))&&!(riga.equals(""))   ){
                        if (riga.equals("[JIF TEMPLATE]")) markJifTemplate=true;

                        // controllo
                        if (
                        riga.startsWith("[TYPE]=") ||
                        riga.startsWith("[NAME]=") ||
                        riga.startsWith("[AUTHOR]=") ||
                        riga.startsWith("[DATE]=") ||
                        riga.startsWith("[VERSION]=") ||
                        riga.startsWith("[COMMENT]=") ||
                        riga.startsWith("[DESCRIPTION]=")
                        ){
                            if (riga.startsWith("[DESCRIPTION]=")) sbdescr
                            .append("[DESCRIPTION]\n").append(riga.substring(14)).append("\n");
                            else sbdescr.append(riga).append("\n");
                        }

                        if (riga.startsWith("[BEGIN]") ){ inCode=true;}
                        if (riga.startsWith("[END]") ){ inCode=false;}

                        else if (
                        !riga.startsWith("[BEGIN]") &&
                        !riga.startsWith("[END]") &&
                        !riga.startsWith("[JIF TEMPLATE]")
                        )
                        {
                            // flag per sapere se sono nel codice
                            if (inCode){
                                sbcode.append(riga).append("\n");
                            }
                        }
                        if (riga.startsWith("[PARAMETERS_BEGIN]") ){
                            sbdescr.append(riga).append("\n");
                            inParameters = true;
                        }
                        if (riga.startsWith("[PARAMETERS_END]") ){
                            sbdescr.append(riga).append("\n");
                            inParameters = false;
                        }

                        //flag per sapere se sono nel codice
                        if (inParameters && !riga.startsWith("[PARAMETERS_BEGIN]")){
                            sbdescr.append(riga).append("\n");
                        }

                    }
                }
                br.close();
                if (!markJifTemplate){
                    JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_ERR_WRONG_FORMAT_FILE"));
                }
                else {
                    // load the textareas
                    this.jTextAreaCode.setText(sbcode.toString());
                    this.jTextAreaCode.setCaretPosition(0);
                    this.jTextAreaDescription.setText(sbdescr.toString());
                    this.jTextAreaDescription.setCaretPosition(0);
                }
            }


        }
        catch (FileNotFoundException e){}
        catch (IOException e){}
    }




    /**
     * Performs a Refresh action to the template tree
     */
    public void refreshTree(){
        repository = new StringBuffer();
        this.jTextAreaCode.setText("");
        this.jTextAreaDescription.setText("");
        this.refreshTree=true;
        top.removeAllChildren();
        treeModel.reload(top);
        loadRecursive(top);
        this.refreshTree=false;
    }



    /**
     * Expands the tree.
     * If expand is true, expands all nodes in the tree.
     * Otherwise, collapses all nodes in the tree.
     * @param tree The Templates tree
     * @param expand Boolean to expanding or collapsing the nodes
     */
    public void expandAll(JTree tree, boolean expand) {
        TreeNode root = (TreeNode)tree.getModel().getRoot();
        // Traverse tree from root
        expandAll(tree, new TreePath(root), expand);
    }
    private void expandAll(JTree tree, TreePath parent, boolean expand) {
        // Traverse children
        TreeNode node = (TreeNode)parent.getLastPathComponent();
        if (node.getChildCount() >= 0) {
            for (Enumeration e=node.children(); e.hasMoreElements(); ) {
                TreeNode n = (TreeNode)e.nextElement();
                TreePath path = parent.pathByAddingChild(n);
                expandAll(tree, path, expand);
            }
        }
        // Expansion or collapse must be done bottom-up
        if (expand) {
            tree.expandPath(parent);
        } else {
            tree.collapsePath(parent);
        }
    }

    /**
     * Expands the first level of template tree
     * @param tree The Template tree
     */
    public void expandFirstLevel(JTree tree){
        TreeNode root = (TreeNode)tree.getModel().getRoot();
        tree.expandPath(new TreePath(root));
    }


private class TemplateRenderer extends DefaultTreeCellRenderer {
ImageIcon staticIcon;
ImageIcon dinamicIcon;

public TemplateRenderer() {
    staticIcon = new ImageIcon(getClass().getResource("/images/TREE_static.png"));
    dinamicIcon = new ImageIcon(getClass().getResource("/images/TREE_dynamic.png"));
}

public Component getTreeCellRendererComponent(JTree tree,Object value,boolean sel,boolean expanded,boolean leaf,int row,boolean hasFocus) {
    super.getTreeCellRendererComponent(tree, value, sel,expanded, leaf, row,hasFocus);
DefaultMutableTreeNode node = (DefaultMutableTreeNode) value;
Object obj = node.getUserObject();
String nodeName = ((Template)obj).Tname;

if(nodeName.endsWith(".jst")) {
    setIcon(staticIcon);
}
else if(nodeName.endsWith(".jdt")) {
    setIcon(dinamicIcon);
}
    return this;
    }
}



/**
 * Rescues parameters for a dynamic template
 * @return String which contains the parameters
 */
public String getParameters(){
    String code = this.jTextAreaDynamicCode.getText();
    StringTokenizer sttok = new StringTokenizer(code,"§");
    String tmp="";
    StringBuffer parameters = new StringBuffer();
    while (sttok.hasMoreTokens()){
        tmp = sttok.nextToken();
        if (tmp.startsWith("*")){
            String result = JOptionPane.showInputDialog(this.jFrameDinamico,java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_INSERT_DESCRIPTION_FOR_PARAMETER")+tmp);
            if (null==result) {
                return null;
            }
            parameters.append(tmp.substring(1)+"°"+result+"\n");
        }
    }
    return parameters.toString();
}



/**
 * Rescues dynamic template in string format to be
 * inserted in your Inform code
 * @return The Template in string format
 */
public String getDynamicTemplate(){
    //    recupero il codice
    //    per ogni parametro, joptionpane.showinputdialog con la descrizione
    //    lo inserisco al posto di *nome
    //    ritorno la stringa così modificata
    String parametri = this.jTextAreaDescription.getText();
    parametri = parametri.substring(
        parametri.indexOf("[PARAMETERS_BEGIN]")+18,
        parametri.indexOf("[PARAMETERS_END]")
    );
    StringTokenizer sttok = new StringTokenizer(parametri,"\n");
    Hashtable htparams = new Hashtable();
    while(sttok.hasMoreTokens()){
        String appoggio = sttok.nextToken();
        StringTokenizer stok = new StringTokenizer(appoggio,"°");
        htparams.put(
        stok.nextToken(),stok.nextToken()
        );
    }

    String code = this.jTextAreaCode.getText();
    sttok = new StringTokenizer(code,"§");
    String tmp="";
    StringBuffer out = new StringBuffer();
    while (sttok.hasMoreTokens()){
        tmp = sttok.nextToken();
        if (tmp.startsWith("*")) {
            String result = JOptionPane.showInputDialog(this,java.util.ResourceBundle.getBundle("JIF").getString("TEMPLATEMANAGER_MSG_INSERT_VALUE_FOR_PARAMETER_")+tmp);
            out.append(result);
        }
        else out.append(tmp);
    }
    return out.toString();
}



/**
 * Rescues Static template in string format to be
 * inserted in your Inform code
 * @return The static template in string format
 */
public String getStaticTemplate(){
    return this.jTextAreaCode.getText();
}



/**
 * Adds the passed template into the repository StringBuffer
 * @param template The Template to be added into the repository
 */
public void addTemplateToRepository(Template template){
    StringBuffer content = new StringBuffer();
    String riga="";
    try{
        BufferedReader br = new BufferedReader(new FileReader(template.Tfile));
        while ((riga = br.readLine())!=null){
            content.append(riga).append("¥");
        }
    }
    catch(FileNotFoundException e){}
    catch(IOException e){}
    repository.append(template.Tname+"¥")
    .append(template.Tfile.getAbsolutePath().substring(template.Tfile.getAbsolutePath().indexOf("config\template")+15)+"¥")
    .append(content.toString())
    .append("\n");
}


/**
 * Deletes all files and subdirectories under dir.
 * Returns true if all deletions were successful.
 * If a deletion fails, the method stops attempting
 * to delete and returns false.
 * @param dir The current directory to be deleted
 * @return False if deletion fails, true if performed
 */
    public static boolean deleteDir(File dir) {
        if (dir.isDirectory()) {
            String[] children = dir.list();
            for (int i=0; i<children.length; i++) {
                boolean success = deleteDir(new File(dir, children[i]));
                if (!success) {
                    return false;
                }
            }
        }

        // The directory is now empty so delete it
        return dir.delete();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonMake;
    private javax.swing.JButton jButtonMakeIstance;
    private javax.swing.JButton jButtonNewDirectory;
    private javax.swing.JButton jButtonNewDynamic;
    private javax.swing.JButton jButtonNewStatic;
    private javax.swing.JButton jButtonRefreshTree;
    private javax.swing.JButton jButtonSaveDynamic;
    private javax.swing.JButton jButtonSaveStatic;
    private javax.swing.JButton jButtonUseSelected;
    private javax.swing.JFrame jFrameDinamico;
    private javax.swing.JFrame jFrameStatico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextAreaCode;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextArea jTextAreaDynamicCode;
    private javax.swing.JTextArea jTextAreaStaticCode;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldAuthorDynamic;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldDateDynamic;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldDescriptionDynamic;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNameDynamic;
    private javax.swing.JTextField jTextFieldTargetDirectory;
    private javax.swing.JTextField jTextFieldTargetDirectoryDynamic;
    private javax.swing.JTextField jTextFieldVersion;
    private javax.swing.JTextField jTextFieldVersionDynamic;
    private javax.swing.JTree jTreeTemplate;
    // End of variables declaration//GEN-END:variables

    private static String templateDirectory="c:\\Jif\\config\\template";
    private DefaultTreeModel treeModel;
    private DefaultMutableTreeNode top;
    private boolean refreshTree=false;
    private File directorySelected;

    private Icon ICON_STATIC;
    private Icon ICON_DINAMIC;
    private StringBuffer repository;
}
